---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Workaround Kibana "Invalid URL" error for ubuntu hostname instance-ubuntu-xx.yy
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Convert hostname to local IPv4
          ansible.builtin.shell: "getent hosts {{ fleet_server_url | \
            urlsplit(\"hostname\") }} | awk '{ print $1 }'"  # noqa: risky-shell-pipe
          changed_when: false
          register: getent_result
        - name: Use IPv4 in fleet_server_url
          ansible.builtin.set_fact:
            fleet_server_url: https://{{ getent_result.stdout_lines[0] }}:8220
    - name: Set fleet_server_hosts
      ansible.builtin.uri:
        method: PUT
        url: http://localhost:5601/api/fleet/settings
        headers:
          kbn-xsrf: true
        body:
          fleet_server_hosts:
            - "{{ fleet_server_url }}"
        body_format: json
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      changed_when: true
    - name: Set fleet-default-output
      ansible.builtin.uri:
        method: PUT
        url: http://localhost:5601/api/fleet/outputs/fleet-default-output
        headers:
          kbn-xsrf: true
        body:
          name: default
          is_default: true
          is_default_monitoring: true
          type: elasticsearch
          hosts:
            - https://grampa:9200
        body_format: json
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      changed_when: true
