---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Wait 200 secs for Elastic Agent warmup
      ansible.builtin.pause:
        seconds: 200
    - name: Check agents state
      ansible.builtin.uri:
        method: GET
        url: http://localhost:5601/api/fleet/agents
        headers:
          kbn-xsrf: true
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
      delegate_to: localhost
      failed_when: false
      register: check_agents_result
    - name: Assert Fleet Server is registed
      ansible.builtin.assert:
        that:
          - check_agents_result.json.list | length == 1
          - check_agents_result.json.list[0].policy_id == 'fleet-server-policy'
          - check_agents_result.json.list[0].status == 'online'
          - check_agents_result.json.list[0].last_checkin_status == 'online'
          - check_agents_result.json.list[0].last_checkin_message == 'Running'
          - check_agents_result.json.list[0].components[0].status == 'HEALTHY'
