---
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE_DISTRO:-ubuntu-22.04}
    image: "antmelekhin/docker-systemd:${MOLECULE_DISTRO:-ubuntu-22.04}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    networks:
      - name: elasticsearch_cluster
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_RUN_TAGS: wipe_elastic_agent
  inventory:
    group_vars:
      all:
      # No parameter required
scenario:
  test_sequence:  # All default steps except idempotence
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
