---
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE_DISTRO:-ubuntu-22.04}
    image: "antmelekhin/docker-systemd:${MOLECULE_DISTRO:-ubuntu-22.04}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    networks:
      - name: elasticsearch_cluster
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_RUN_TAGS: wipe_elastic_agent
  inventory:
    group_vars:
      all:
        # They are parameters to enroll EA
        elastic_agent_version: "{{ lookup('ansible.builtin.env', 'STACK_VERSION') }}"
        elastic_agent_kibana_host: https://localhost:5601
        elastic_agent_insecure: true
        elastic_agent_enrollment_fleet_server_url: https://ecp-fleet-server:8220
        fleet_server_elasticsearch_user: elastic
        fleet_server_elasticsearch_password: change_me
scenario:
  test_sequence:  # All default steps except idempotence
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
