---
- name: Prepare Elastic agent files
  import_tasks: get_files.yml

- name: Enroll Elastic Agent
  import_tasks: enroll_agent.yml

- name: Uninstall Elastic Agent
  import_tasks: uninstall_agent.yml
  tags:
  - never
  - wipe_elastic_agent
