---
- name: Prepare Elastic agent files
  ansible.builtin.import_tasks: get_files.yml

- name: Enroll Elastic Agent
  ansible.builtin.import_tasks: enroll_agent.yml

- name: Uninstall Elastic Agent
  ansible.builtin.import_tasks: uninstall_agent.yml
  tags:
    - never
    - wipe_elastic_agent
