---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  roles:
    - jpmat296.elastic_agent
  module_defaults:
    ansible.builtin.get_url:
      # 2024-05: To workaround error:
      # Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
      # unable to get local issuer certificate (_ssl.c:1007)>
      # "url": "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.0-linux-x86_64.tar.gz
      validate_certs: false
