---
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE_DISTRO:-ubuntu-22.04}
    image: "antmelekhin/docker-systemd:${MOLECULE_DISTRO:-ubuntu-22.04}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    networks:
      - name: elasticsearch_cluster
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_SKIP_TAGS: delete_install_files
  inventory:
    group_vars:
      all:
        elastic_agent_version: "{{ lookup('ansible.builtin.env', 'STACK_VERSION') }}"
        elastic_agent_standalone_elasticsearch_urls:
          - https://{{ lookup("pipe", "hostname") }}:9200
        elastic_agent_verification_hostname: instance-${MOLECULE_DISTRO:-ubuntu-22.04}
        elastic_agent_standalone_api_key: "{{ lookup('file', '/tmp/molecule/\
          api_key_molecule-automatic-test-' + lookup('ansible.builtin.env', \
          'MOLECULE_SCENARIO_NAME')) }}"
        elastic_agent_ssl_verification_mode: none
