---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt packages list
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == 'Ubuntu'
    - name: Install misc packages required
      ansible.builtin.package:
        name: python3-psutil
