---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Wait 200 secs for Elastic Agent warmup
      ansible.builtin.pause:
        seconds: 200
    - name: Check agents state
      ansible.builtin.uri:
        method: GET
        # KQL filter is active : status: online and policy_id : "fleet-default-policy"
        url: "{{ elastic_agent_kibana_url }}/api/fleet/agents?\
          kuery=status%20%3A%20online%20and%20policy_id%20%3A%20%22fleet-default-policy%22"
        headers:
          kbn-xsrf: true
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      register: check_agents_result
    - name: DEBUG check_agents_result
      ansible.builtin.debug:
        var: check_agents_result
    - name: DEBUG 1 - Check agents state 2
      ansible.builtin.debug:
        msg: "url is {{ elastic_agent_kibana_url }}/api/fleet/agents"
      delegate_to: localhost
    - name: DEBUG 2 - Check agents state 2
      ansible.builtin.debug:
        msg: "url is {{ elastic_agent_kibana_url }}/api/fleet/agents"
    - name: Check agents state 2
      ansible.builtin.uri:
        method: GET
        url: "{{ elastic_agent_kibana_url }}/api/fleet/agents"
        headers:
          kbn-xsrf: true
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      register: check_agents_result2
    - name: DEBUG check_agents_result2
      ansible.builtin.debug:
        var: check_agents_result2
    - name: DEBUG Fleet server hosts
      ansible.builtin.uri:
        method: GET
        url: "{{ elastic_agent_kibana_url }}/api/fleet/settings"
        headers:
          kbn-xsrf: true
        user: "{{ fleet_server_elasticsearch_user }}"
        password: "{{ fleet_server_elasticsearch_password }}"
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      register: fleet_settings_json
    - name: Assert new Elastic Agent is registed
      ansible.builtin.assert:
        that:
          - check_agents_result.json.list | length == 1
          - check_agents_result.json.list[0].policy_id == 'fleet-default-policy'
          - check_agents_result.json.list[0].status == 'online'
          - check_agents_result.json.list[0].last_checkin_status == 'online'
          - check_agents_result.json.list[0].last_checkin_message == 'Running'
