---
name: 8_13 Scenarios with ES + KB + Fleet
'on':
  pull_request:
  push:

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          # - 8.7.0   # -- base-path not supported
          # - 8.10.4  # -- base-path not supported
          # - 8.12.2
          - 8.13.1
          - 8.13.4
        distro:
          - ubuntu-22.04
          # - rockylinux-9

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: DEBUG - BEFORE
        run: |
          hostname
          export

      - name: Start containers
        run: |
          cd molecule/setup/es_kb_fleet
          sed -i 's/^STACK_VERSION=.*/STACK_VERSION=${{ matrix.version }}/g' .env
          ./elastic-container.sh start

      - name: Install test dependencies.
        run: pip3 install ansible molecule 'molecule-plugins[docker]'

      - name: Run Molecule tests.
        run: |
          STACK_VERSION=${{ matrix.version }} molecule -vvv test -s enroll --destroy never
          # STACK_VERSION=${{ matrix.version }} molecule test -s uninstall --destroy never
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: DEBUG - STATE
        if: always()
        run: |
          docker ps -all || true
          docker exec instance-${{ matrix.distro }} ps -fC elastic-agent || true
          docker exec instance-${{ matrix.distro }} find /opt/Elastic/Agent -iname "*.log" -o -iname "*.ndjson" || true
          docker exec instance-${{ matrix.distro }} systemctl status elastic-agent || true
          docker exec instance-${{ matrix.distro }} ls -l /opt/Elastic/Agent/data || true
          export DIREA=$(docker exec instance-${{ matrix.distro }} bash -c \
            'ls -d /opt/Elastic/Agent/data/*' | grep elastic-agent-)
          docker exec instance-${{ matrix.distro }} ls -lrt $DIREA/logs || true

      - name: DEBUG - Docker
        if: always()
        run: |
          mkdir -p ~/logs || true
          docker inspect ecp-fleet-server > ~/logs/docker-inspect-ecp-fleet-server || true

      - name: DEBUG - Copy before updload
        if: always()
        run: |
          mkdir -p ~/logs
          export DIREA=$(docker exec instance-${{ matrix.distro }} bash -c \
            'ls -d /opt/Elastic/Agent/data/*' | grep elastic-agent-)
          docker cp "instance-${{ matrix.distro }}:$DIREA/logs" ~/logs/ || true
          sudo chmod -R 777 ~/logs || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact-8_13-${{ matrix.distro }}-${{ matrix.version }}
          path: |
            ~/logs

      - name: Stop containers
        if: always()
        run: |
          cd molecule/setup/es_kb_fleet
          STACK_VERSION=${{ matrix.version }} ./elastic-container.sh destroy
