---
name: Scenarios with ES + KB
'on':
  pull_request:
  push:

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 8.7.0   # -- base-path not supported
          - 8.10.4  # -- base-path not supported
          - 8.12.2
          - 8.14.2
        distro:
          - ubuntu-22.04
          - rockylinux-9

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Start containers
        run: |
          cd molecule/setup/es_kb
          STACK_VERSION=${{ matrix.version }} docker-compose up -d

      - name: Install test dependencies.
        run: pip3 install ansible molecule 'molecule-plugins[docker]'

      - name: Run Molecule tests.
        run: |
          STACK_VERSION=${{ matrix.version }} molecule test -s default
          STACK_VERSION=${{ matrix.version }} molecule test -s fleet
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Stop containers
        if: always()
        run: |
          cd molecule/setup/es_kb
          docker-compose down || true
